# Site settings
title: Viljamaa DSP
email: blank@blank.com
url: "http://www.mviljamaa.github.io"
description: "Computational sound development"
baseurl: ""
highlighter: rouge
safe: true
lsi: false
source:      .
# languages_iso: [english]
# languages: [english]
# languages_names: [english]
# Build settings
markdown: kramdown
permalink: pretty
