# Site settings
title: Viljamaa DSP
email: email@email.com
url: "http://www.mviljamaa.github.io"
description: "Computational sound development"
baseurl: ""
highlighter: pygments
safe: true
lsi: false
source:      .
languages_iso: [en]
languages: [en]
languages_names: [english]
# Build settings
markdown: kramdown
permalink: pretty
